### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by OsakiTsukiko** [OsakiTsukiko/brulee#3]
Main:
- [ ] Make this list.

Random: 
- [ ] Add images to readme file.. pictures are fun :)
- [ ] Add workflows to compile brulee for all platforms.
- [ ] Update Readme (renderer (the framework) fell through)
